INSERT INTO JEDALEN (NAZOV, MESTO, ULICA, CISLO_DOMU, PERCENTO_NAVYSENIA) 
  VALUES (NAZOV, MESTO, ULICA, CISLO_DOMU, PERCENTO_NAVYSENIA);

INSERT INTO ZAMESTNANEC_JEDALNE (MENO, PRIEZVISKO, DATUM_NARODENIA, POHLAVIE, ID_JEDALNE, ID_POZICIE) 
  VALUES (MENO, PRIEZVISKO, DATUM_NARODENIA, POHLAVIE, ID_JEDALNE, ID_POZICIE);

INSERT INTO POZICIA (NAZOV, HODINOVA_MZDA, POZNAMKA) 
  VALUES (NAZOV, HODINOVA_MZDA, POZNAMKA);
  
INSERT INTO JEDLO (NAZOV, GRAMAZ, CENA) 
  VALUES (NAZOV, GRAMAZ, CENA);
  
INSERT INTO MENU (NAZOV) 
  VALUES (NAZOV);

INSERT INTO OBSAHUJE (ID_MENU, ID_JEDLA) 
  VALUES (ID_MENU, ID_JEDLA);

INSERT INTO PONUKA (ID_JEDALNE, ID_MENU, DATUM) 
  VALUES (ID_JEDALNE, ID_MENU, DATUM);

INSERT INTO PREDAVA (ID_JEDALNE, ID_JEDLA, DATUM, CAS, POCET_KUSOV) 
  VALUES (ID_JEDALNE, ID_JEDLA, DATUM, CAS, POCET_KUSOV);
  
INSERT INTO PRODUKCIA_ZISKU (ID_JEDALNE, MESIAC, ROK, ZISK)
  VALUES (ID_JEDALNE, MESIAC, ROK, ZISK);
  
  
  
  
  

  
