select pre.datum
,pre.cas
,jed.nazov as "Nazov jedalne"
,j.nazov as "Nazov jedla"
,pre.POCET_KUSOV * j.CENA || '€'  as "Celkova cena nakupu"  
,ROUND(pre.POCET_KUSOV * j.CENA * (jed.PERCENTO_NAVYSENIA/100),2)|| '€' as "Zisk z nakupu" 
from  predava 
pre inner join jedlo j 
on pre.ID_JEDLA = j.ID_JEDLA 
inner join jedalen jed
on pre.ID_JEDALNE = jed.ID_JEDALNE
order by pre.cas
;
SELECT j.MESTO, COUNT(*) AS "POCET JEDALNI" FROM JEDALEN j GROUP BY j.MESTO; 

SELECT * FROM 
(SELECT j.MESTO, j.NAZOV, j.PERCENTO_NAVYSENIA FROM JEDALEN j ORDER BY j.PERCENTO_NAVYSENIA)
 WHERE ROWNUM <= 1;
 
SELECT j.NAZOV, z.POHLAVIE, COUNT(*) AS "POCET" FROM ZAMESTNANEC_JEDALNE z NATURAL JOIN JEDALEN j GROUP BY z.POHLAVIE, j.NAZOV ORDER BY 1;

SELECT j.NAZOV, COUNT(z.POHLAVIE) AS "Muzi" FROM ZAMESTNANEC_JEDALNE z NATURAL JOIN JEDALEN j WHERE z.POHLAVIE = 'M' GROUP BY z.POHLAVIE, j.NAZOV

SELECT z.MENO, z.PRIEZVISKO, p.NAZOV FROM ZAMESTNANEC_JEDALNE z NATURAL JOIN POZICIA p WHERE z.ID_JEDALNE = 1;

SELECT p.NAZOV, p.HODINOVA_MZDA*120 AS "PRIEMERNA MESACNA MZDA" FROM pozicia p;

SELECT j.NAZOV, AVG(pr.ZISK) AS "PRIEMERNY ZISK" FROM PRODUKCIA_ZISKU pr NATURAL JOIN JEDALEN j GROUP BY j.NAZOV;

SELECT * FROM OBSAHUJE o NATURAL JOIN MENU m;
SELECT * FROM OBSAHUJE o NATURAL JOIN JEDLO j; 










